name: Swift macOS build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build-macos:
    timeout-minutes: 60
    runs-on: [self-hosted, macos-12]

    steps:
    - name: Wipe gitconfig
      run: echo "" > ~/.gitconfig
    - uses: actions/checkout@v3
    - name: Git URL token override
      run: git config --global url."https://ordo-ci:${{ secrets.CI_MACHINE_PAT }}@github.com".insteadOf "https://github.com"
    - name: Swift version
      run: swift --version
    - name: Brew environment
      run: echo "/opt/homebrew/bin:/usr/local/bin" >> $GITHUB_PATH
    - name: Run tests
      run: swift test --parallel
    - name: Wipe gitconfig
      run: echo "" > ~/.gitconfig
