name: Swift build documentation

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-documentation:

# https://github.com/actions/runner/issues/520
    runs-on: [self-hosted, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Extract default SPM library target
      id: spm_target
      run: |
        SPM_DEFAULT_TARGET=$(swift package dump-package | jq -r '.products | .[] | select(.type | has("library")) | .name' | head -1)
        echo "::set-output name=spmlibrarytarget::$SPM_DEFAULT_TARGET"
    - run: mkdir -p ./docs
      if: ${{ steps.spm_target.outputs.spmlibrarytarget }} != ''
    - uses: fwcd/swift-docc-action@v1
      with:
          target: ${{ steps.spm_target.outputs.spmlibrarytarget }}
          output: ./docs
          hosting-base-path: ${{ github.event.repository.name }}
          disable-indexing: 'true'
          transform-for-static-hosting: 'true'
    - run: tar czpf Documentation.tar.gz ./docs
      if: ${{ steps.spm_target.outputs.spmlibrarytarget }} != ''
    - uses: actions/upload-artifact@v3
      with:
        name: Documentation
        path: Documentation.tar.gz
