name: Swift thread sanitizer macOS

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    runs-on: [self-hosted, macos-12]

    steps:
    - name: Wipe gitconfig
      run: echo "" > ~/.gitconfig

    - uses: actions/checkout@v3

    - name: Git URL token override
      run: git config --global url."https://ordo-ci:${{ secrets.CI_MACHINE_PAT }}@github.com".insteadOf "https://github.com"

    - name: Clean before debug build thread sanitizier
      run: swift package clean

    - name: Run thread sanitizer
      run: swift test --sanitize=thread

    - name: Clean before release build thread sanitizier
      run: swift package clean
      
    - name: Run thread sanitizer on release build
      run: swift test --sanitize=thread -c release -Xswiftc -enable-testing | swift demangle

     - name: Wipe gitconfig
      run: echo "" > ~/.gitconfig
